### ISSUE TITLE
how to use justify like css

### ISSUE THREAD

**Issue by bobwatcherx** [Claus1/unigui#5]
how to use SpaceBeween , spaceAroud,Center layout in block

my code  

bt = Block("Dwdq",
	[
		Button("showme",ganti,icon="check"),
		Edit("Dwqdwq","")
	],width=500,scroll=True)

**Comment by Claus1** [comment]
All designer job is done by the front-end auto-designer. You have just combine gui elements to preferable order, and that is all.  unigui tries to follow Material design specs automatically.
